#!/bin/zsh

./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0287.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0344.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0355.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0540.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0553.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0595.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0651.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0668.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0696.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0715.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0725.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0934.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_0993.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1009.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1035.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1074.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1092.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1128.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1137.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1187.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1239.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1287.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1339.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1401.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1451.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1544.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1545.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1597.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_1602.jpg
./picts-compressor -c0 ~/Desktop/Test\ Photos/IMG_2695.jpg